CREATE TABLE NguoiDung(
    Email VARCHAR(100) PRIMARY KEY,
    HoTenNguoiDung VARCHAR(50) NOT NULL,
    TenDangNhap VARCHAR(100) NOT NULL,
    MatKhau VARCHAR(100) NOT NULL
);
CREATE TABLE BaiViet(
    ID_BaiViet INT AUTO_INCREMENT PRIMARY KEY,
    TieuDe VARCHAR(100) NOT NULL,
    NoiDung BLOB,
    NgayDang DATETIME,
    ID_NguoiDung VARCHAR(100) NOT NULL,
    ID_The_Loai VARCHAR(100) NOT NULL
);
CREATE TABLE Pics(
    ID_Anh INT AUTO_INCREMENT PRIMARY KEY,
    Ten_File_Anh VARCHAR(200) NOT NULL,
    Duoi_File_Anh VARCHAR(50) NOT NULL, 
    Kich_Co_Anh INT NOT NULL,
    Du_Lieu_Anh mediumblob NOT NULL,
    ID_BaiViet VARCHAR(100) NOT NULL
);
CREATE TABLE Videos(
    ID_Video INT AUTO_INCREMENT PRIMARY KEY,
    Ten_File_Video VARCHAR(200) NOT NULL,
    Duoi_file VARCHAR(50) NOT NULL, 
    Kich_Co_Video INT NOT NULL,
    Du_Lieu_Video mediumblob NOT NULL,
    ID_BaiViet VARCHAR(100) NOT NULL
);
CREATE TABLE TheLoai(
    ID_TheLoai VARCHAR(100) PRIMARY KEY,
    Ten_TheLoai VARCHAR(100) NOT NULL
);